domaci ukol
Saljack/kpj-annotation-processors pull request #3
Opened 2022-04-26 08:04 UTC by skrabets

2022-04-26 21:45 UTC, Saljack requested changes
Dej si pozor na to co commitujes a kam.

2022-04-26 21:45 UTC, Saljack commented on src/main/java/cz/inventi/kpj/annotation/processors/UserDTO.java
> +import lombok.Getter;
Tady se nema nic upravovat

2022-04-26 21:45 UTC, Saljack commented on src/main/java/cz/inventi/kpj/annotation/processors/User.java
> +  public User() {
Precti si jeste jednou javadoc ke class kde je napsane co mas udelat a koukni na https://projectlombok.org/features/all na anotace, ktere se pro to nejlepe hodi (hint jedna anotace o ktere jsem mluvil groupuje vic anotaci do sebe) melo by ti stacit celkem 3 anotace (mozna 2)

2022-04-26 21:45 UTC, Saljack commented on src/main/java/cz/inventi/kpj/annotation/processors/KpjAnnotationProcessors.java
> +    UserDTO userDTO = mapper.INSTANCE.userToUserDTO(user);
Tohle je zbytecne

2022-04-27 12:11 UTC, skrabec commented on src/main/java/cz/inventi/kpj/annotation/processors/User.java
> +  public User() {
resolved

2022-04-27 13:54 UTC, Saljack commented on src/main/java/cz/inventi/kpj/annotation/processors/User.java
> +  public User() {
Tohle opravene pridej jenom anotace a ne zadne consturctory atp. staci ti anotace s `@*Consturctor` a `@Date` - ktera generuje gettery settery, equals, hashCode a RequredArgsConstructor

2022-04-27 14:06 UTC, Saljack commented
Az pridas ty annotace tak mas 2 body

2022-04-27 15:35 UTC, skrabec commented on src/main/java/cz/inventi/kpj/annotation/processors/User.java
> +  public User() {
Ten Lombook je nadherny, jsem zamilovany! :)

2022-04-28 06:35 UTC, Saljack commented
Ok mas dva body.

2022-04-28 06:35 UTC, closed without merging